name: Docker Image CI

on:
  push:
    branches: ["deploy"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub 
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build -t quiz-slayer-env Frontend/.
    - name: Push Docker image
      run: docker push thomastejedor/quiz-slayer-env:latest
    
