name: Docker Image CI

on:
  push:
    branches: ["deploy"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login Dockerhub 
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
    - name: Build Docker Container
      uses: docker/build-push-action@v6
      with:
        context: ./Frontend
        tags: thomastejedor/quiz-slayer-env:latest
        secrets: |
          "PRIVATE_KEY=${{secrets.PRIVATE_SSL_KEY}}"
          "SSL_CERT=${{secrets.SSL_CERT}}"

    
